version: '2.4'
services:
  dev_enviroment:
    build: ./Docker-image
    #volumes: 
     # - ./wokring_dir
    expose: 
      - '22'
    ports:
      - '5001:22'
    stdin_open: true
    cpu_count: 2
    cpuset: 0,1
    mem_limit: '5000000000'
